"""Create categories table

Revision ID: aced2b249851
Revises: b4c86e7faefd
Create Date: 2025-05-01 16:52:00.642540

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aced2b249851"
down_revision: Union[str, None] = "0713bf0c584d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("financialrecords") as batch_op:
        batch_op.add_column(sa.Column("category_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            "category_id", "categories", ["category_id"], ["id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("financialrecords") as batch_op:
        batch_op.drop_constraint("category_id", type_="foreignkey")
        batch_op.drop_column("category_id")
    op.drop_table("categories")
    # ### end Alembic commands ###
