"""Fill Categories with init data

Revision ID: b603996f3a4f
Revises: aced2b249851
Create Date: 2025-05-01 19:53:57.986197

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b603996f3a4f"
down_revision: Union[str, None] = "aced2b249851"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    categories_table = sa.table(
        "categories", sa.Column("name", sa.String(30)), sa.Column("id", sa.Integer)
    )

    op.bulk_insert(
        categories_table,
        [
            {"name": "Other"},
            {"name": "Food"},
            {"name": "Transport"},
            {"name": "Housing"},
            {"name": "Entertainment"},
            {"name": "Health"},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DELETE FROM categories WHERE name IN ("
        "'Other', 'Food', 'Transport', 'Housing', 'Entertainment', 'Health'"
        ")"
    )
    # ### end Alembic commands ###
